'use server'
import { revalidatePath } from 'next/cache'
import { prisma } from '@/lib/prisma'
import { requireAdmin } from '@/lib/admin-guard'
import { z } from 'zod'

const d = (v?: string) => (v ? new Date(v) : null)

// ─── Services ───
const serviceSchema = z.object({ title: z.string().min(1), slug: z.string().min(1), description: z.string().optional(), icon: z.string().optional(), features: z.array(z.string()).default([]), priceInfo: z.string().optional(), order: z.number().default(0), isActive: z.boolean().default(true) })
export async function createService(input: z.infer<typeof serviceSchema>) { try { await requireAdmin(); const p = serviceSchema.parse(input); const r = await prisma.service.create({ data: p }); revalidatePath('/'); revalidatePath('/admin/services'); return { success: true, id: r.id } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function updateService(id: string, input: z.infer<typeof serviceSchema>) { try { await requireAdmin(); const p = serviceSchema.parse(input); await prisma.service.update({ where: { id }, data: p }); revalidatePath('/'); revalidatePath('/admin/services'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function deleteService(id: string) { try { await requireAdmin(); await prisma.service.delete({ where: { id } }); revalidatePath('/'); revalidatePath('/admin/services'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }

// ─── Skills ───
const skillSchema = z.object({ name: z.string().min(1), category: z.string().min(1), proficiency: z.number().min(0).max(100).optional(), icon: z.string().optional(), order: z.number().default(0) })
export async function createSkill(input: z.infer<typeof skillSchema>) { try { await requireAdmin(); const p = skillSchema.parse(input); const r = await prisma.skill.create({ data: p }); revalidatePath('/'); revalidatePath('/admin/skills'); return { success: true, id: r.id } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function updateSkill(id: string, input: z.infer<typeof skillSchema>) { try { await requireAdmin(); const p = skillSchema.parse(input); await prisma.skill.update({ where: { id }, data: p }); revalidatePath('/'); revalidatePath('/admin/skills'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function deleteSkill(id: string) { try { await requireAdmin(); await prisma.skill.delete({ where: { id } }); revalidatePath('/'); revalidatePath('/admin/skills'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }

// ─── Experience ───
const expSchema = z.object({ company: z.string().min(1), role: z.string().min(1), type: z.string().default('fulltime'), location: z.string().optional(), startDate: z.string().min(1), endDate: z.string().optional(), isCurrent: z.boolean().default(false), description: z.string().optional(), achievements: z.array(z.string()).default([]), companyUrl: z.string().optional(), logo: z.string().optional(), order: z.number().default(0) })
export async function createExperience(input: z.infer<typeof expSchema>) { try { await requireAdmin(); const p = expSchema.parse(input); const r = await prisma.experience.create({ data: { ...p, startDate: new Date(p.startDate), endDate: d(p.endDate), companyUrl: p.companyUrl || null, logo: p.logo || null, location: p.location || null, description: p.description || null } }); revalidatePath('/about'); revalidatePath('/admin/experience'); return { success: true, id: r.id } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function updateExperience(id: string, input: z.infer<typeof expSchema>) { try { await requireAdmin(); const p = expSchema.parse(input); await prisma.experience.update({ where: { id }, data: { ...p, startDate: new Date(p.startDate), endDate: d(p.endDate), companyUrl: p.companyUrl || null, logo: p.logo || null, location: p.location || null, description: p.description || null } }); revalidatePath('/about'); revalidatePath('/admin/experience'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function deleteExperience(id: string) { try { await requireAdmin(); await prisma.experience.delete({ where: { id } }); revalidatePath('/about'); revalidatePath('/admin/experience'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }

// ─── Education ───
const eduSchema = z.object({ institution: z.string().min(1), degree: z.string().min(1), field: z.string().optional(), startDate: z.string().min(1), endDate: z.string().optional(), isCurrent: z.boolean().default(false), description: z.string().optional(), logo: z.string().optional(), order: z.number().default(0) })
export async function createEducation(input: z.infer<typeof eduSchema>) { try { await requireAdmin(); const p = eduSchema.parse(input); const r = await prisma.education.create({ data: { ...p, startDate: new Date(p.startDate), endDate: d(p.endDate), field: p.field || null, logo: p.logo || null, description: p.description || null } }); revalidatePath('/about'); revalidatePath('/admin/education'); return { success: true, id: r.id } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function updateEducation(id: string, input: z.infer<typeof eduSchema>) { try { await requireAdmin(); const p = eduSchema.parse(input); await prisma.education.update({ where: { id }, data: { ...p, startDate: new Date(p.startDate), endDate: d(p.endDate), field: p.field || null, logo: p.logo || null, description: p.description || null } }); revalidatePath('/about'); revalidatePath('/admin/education'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function deleteEducation(id: string) { try { await requireAdmin(); await prisma.education.delete({ where: { id } }); revalidatePath('/about'); revalidatePath('/admin/education'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }

// ─── Testimonials ───
const testSchema = z.object({ clientName: z.string().min(1), clientRole: z.string().optional(), company: z.string().optional(), content: z.string().min(1), image: z.string().optional(), logo: z.string().optional(), rating: z.number().min(1).max(5).optional(), projectId: z.string().optional(), isActive: z.boolean().default(true), order: z.number().default(0) })
export async function createTestimonial(input: z.infer<typeof testSchema>) { try { await requireAdmin(); const p = testSchema.parse(input); const r = await prisma.testimonial.create({ data: { ...p, clientRole: p.clientRole || null, company: p.company || null, image: p.image || null, logo: p.logo || null, projectId: p.projectId || null } }); revalidatePath('/'); revalidatePath('/admin/testimonials'); return { success: true, id: r.id } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function updateTestimonial(id: string, input: z.infer<typeof testSchema>) { try { await requireAdmin(); const p = testSchema.parse(input); await prisma.testimonial.update({ where: { id }, data: { ...p, clientRole: p.clientRole || null, company: p.company || null, image: p.image || null, logo: p.logo || null, projectId: p.projectId || null } }); revalidatePath('/'); revalidatePath('/admin/testimonials'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function deleteTestimonial(id: string) { try { await requireAdmin(); await prisma.testimonial.delete({ where: { id } }); revalidatePath('/'); revalidatePath('/admin/testimonials'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }

// ─── Certifications ───
const certSchema = z.object({ name: z.string().min(1), issuer: z.string().min(1), issueDate: z.string().min(1), expiryDate: z.string().optional(), credentialUrl: z.string().optional(), image: z.string().optional(), order: z.number().default(0) })
export async function createCertification(input: z.infer<typeof certSchema>) { try { await requireAdmin(); const p = certSchema.parse(input); const r = await prisma.certification.create({ data: { ...p, issueDate: new Date(p.issueDate), expiryDate: d(p.expiryDate), credentialUrl: p.credentialUrl || null, image: p.image || null } }); revalidatePath('/about'); revalidatePath('/admin/certifications'); return { success: true, id: r.id } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function updateCertification(id: string, input: z.infer<typeof certSchema>) { try { await requireAdmin(); const p = certSchema.parse(input); await prisma.certification.update({ where: { id }, data: { ...p, issueDate: new Date(p.issueDate), expiryDate: d(p.expiryDate), credentialUrl: p.credentialUrl || null, image: p.image || null } }); revalidatePath('/about'); revalidatePath('/admin/certifications'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }
export async function deleteCertification(id: string) { try { await requireAdmin(); await prisma.certification.delete({ where: { id } }); revalidatePath('/about'); revalidatePath('/admin/certifications'); return { success: true } } catch (e: unknown) { return { success: false, error: e instanceof Error ? e.message : 'Unexpected error' } } }